base_url = "https://lore.earth"
compile_sass = true
minify_html = true
# build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
author = "Lore"
title = "lore.earth"
description = "Excerpts from an Existence at Ease"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
render_emoji = true

# [search]
# index_format = "elasticlunr_javascript"

[extra]
menu_items = [
    { name = "audio", url = "/audio/" },
    { name = "photography", url = "/photography/" },
    { name = "writing", url = "/writing/" },
    { name = "tags", url = "/tags/" },
]
