base_url = "https://lore.earth"
compile_sass = true
minify_html = true
# build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
author = "Lore"
title = "lore.earth"
description = "Excerpts from an Existence at Ease"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
render_emoji = true

# [search]
# index_format = "elasticlunr_javascript"

[extra]
# Theme color for meta tags (hex value)
# This color is used for:
# - Android Chrome's address bar color
# - iOS Safari's status bar color
# - Windows tile color
# - PWA theme color
# Default: "#000000" (black)
# Examples: "#dc2626" (red), "#2563eb" (blue), "#059669" (green)
theme_color_hex = "#000000"
menu_items = [
    { name = "audio", url = "/audio/" },
    { name = "photography", url = "/photography/" },
    { name = "writing", url = "/writing/" },
    { name = "tags", url = "/tags/" },
]
