# fly.toml app configuration file generated for lore-earth on 2025-07-01T01:39:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lore-earth'
primary_region = 'iad'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[[statics]]
url_prefix = "/"
guest_path = "/"
tigris_bucket = "lore-earth"
index_document = "index.html"
